chore: add renaming things

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -34,10 +34,23 @@ jobs:
             ${{ runner.os }}-cargo-
       - run: cargo build --release -j 4
       - run: copy target\release\Zed.exe target\release\Zed-windows-amd64.exe
+      - run: |
+          if [ -f target\\release\\Zed-windows-amd64.exe ]; then
+            echo "Build successful, file exists."
+          else
+            echo "Build failed, file does not exist."
+            exit 1
+          fi
+      - name: Set version tag
+        id: set_version
+        run: |
+          LATEST_TAG=$(curl -s https://api.github.com/repos/zed-industries/zed/releases/latest | jq -r .tag_name)
+          echo "NEXT_VER_CODE=$LATEST_TAG" >> $GITHUB_ENV
+      - run: rename target\\release\\Zed-windows-amd64.exe target\\release\\Zed-windows-amd64-${{ env.NEXT_VER_CODE }}.exe
       - uses: actions/upload-artifact@v4
         with:
           name: Zed-windows-amd64
-          path: target\release\Zed-windows-amd64.exe
+          path: target\\release\\zed-windows-amd64-${{ env.NEXT_VER_CODE }}.exe
 
   upload-to-release:
     runs-on: ubuntu-latest
@@ -67,23 +80,6 @@ jobs:
           echo "$BODY" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
-      - name: Set next version tag
-        id: next_ver_code
-        run: |
-          LATEST_TAG=$(curl -s https://api.github.com/repos/zed-industries/zed/releases/latest | jq -r .tag_name)
-          echo "NEXT_VER_CODE=$LATEST_TAG" >> $GITHUB_ENV
-          cp target/release/Zed.exe target/release/Zed-windows-amd64-${{ env.NEXT_VER_CODE }}.exe
-
-      - uses: actions/upload-artifact@v4
-        with:
-          name: Zed-windows-amd64-${{ env.NEXT_VER_CODE }}
-          path: target/release/Zed-windows-amd64-${{ env.NEXT_VER_CODE }}.exe
-
-      - name: List build artifacts
-        run: |
-          echo "Contents of current directory:"
-          ls -R
-
       - name: Set release info
         run: |
           if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
@@ -101,7 +97,7 @@ jobs:
           tag: ${{ env.NEXT_VER_CODE }}
           body: ${{ env.RELEASE_BODY }}
           repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: Zed-windows-amd64${VERSION}.exe
+          file: target/release/Zed-windows-amd64-${{ env.NEXT_VER_CODE }}.exe
           overwrite: true
 
       - uses: actions/checkout@v4
